### ISSUE TITLE
Fix periodic tests on 2a prod

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#442]
Tests can not obtain user token. Try to switch email to lowercase (update creds in vault).

**Comment by Katka92** [comment]
Credentials changed in vault, did not help. Can not reproduce it localy.

**Comment by ibuziuk** [comment]
@Katka92 any investigation about details? does it happen for a particular user? what is the exact error message?

**Comment by Katka92** [comment]
Error message is:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.1:verify (default) on project functional-tests: There are test failures.
[ERROR] 
[ERROR] Please refer to /root/rh-che/functional-tests/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] Unable to create injector, see the following errors:
[ERROR] 
[ERROR] 1) Error injecting constructor, java.lang.RuntimeException: Failed to get access token for user '****'
[ERROR] at org.eclipse.che.selenium.core.user.MultiUserCheDefaultTestUserProvider.<init>(MultiUserCheDefaultTestUserProvider.java:46)
[ERROR] at org.eclipse.che.selenium.core.user.MultiUserCheDefaultTestUserProvider.class(MultiUserCheDefaultTestUserProvider.java:29)
[ERROR] while locating org.eclipse.che.selenium.core.user.MultiUserCheDefaultTestUserProvider
[ERROR] while locating org.eclipse.che.selenium.core.provider.DefaultTestUserProvider
[ERROR] while locating org.eclipse.che.selenium.core.user.DefaultTestUser
[ERROR] for the 5th parameter of org.eclipse.che.selenium.core.workspace.CheTestWorkspaceProvider.<init>(CheTestWorkspaceProvider.java:64)
[ERROR] at org.eclipse.che.selenium.core.workspace.CheTestWorkspaceProvider.class(CheTestWorkspaceProvider.java:39)
[ERROR] while locating org.eclipse.che.selenium.core.workspace.CheTestWorkspaceProvider
[ERROR] at org.eclipse.che.selenium.core.CheSeleniumSuiteModule.configure(CheSeleniumSuiteModule.java:108) (via modules: com.google.inject.util.Modules$OverrideModule -> org.eclipse.che.selenium.core.CheSeleniumSuiteModule)
[ERROR] while locating org.eclipse.che.selenium.core.workspace.TestWorkspaceProvider
```
This happens to user ```osiotest2aProd``` on production and ```osio-ci-preview-rhche-periodical```. 

This is error from upstream che classes that we are re-using. I've re-added users to Vault to make sure that data in vault are correct (we still don't have ```view``` rights here). 
I've tried to run tests from IDE and worked fine, I've tried that from Docker and I wasn't able to reproduce that either.

**Comment by Katka92** [comment]
Tried again locally, running tests by script and docker - still not able to reproduce. Contacting service delivery to check credentials in vault.

**Comment by Katka92** [comment]
Some typos found in job definition but didn't seem to help. Change user to newly created osiotest2aprod2.

**Comment by Katka92** [comment]
Incorect value of enviroment variable was set. Both jobs for productio and prod-preview are green again. Closing.
